# Generated by Django 4.0.2 on 2022-03-05 08:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_slug_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='get_full_name', unique=True),
        ),
    ]
