# Generated by Django 4.0.2 on 2022-03-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employee_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetrow',
            old_name='hours_worked',
            new_name='worked_seconds',
        ),
    ]
