# Generated by Django 4.0.2 on 2022-03-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_hours_worked_timesheetrow_worked_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tutorial_done',
            field=models.BooleanField(default=False),
        ),
    ]
