# Generated by Django 4.0.2 on 2022-03-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_penalty_valid_for_day_count_penaltyclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltyclaim',
            name='claimed_seconds',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='penaltyclaim',
            name='penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.penaltytype'),
        ),
    ]
