# Generated by Django 4.0.2 on 2022-03-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_penaltyclaim_claimed_seconds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='duration',
            new_name='_duration',
        ),
    ]
