# Generated by Django 4.0.2 on 2022-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_duration_timesheet__duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penaltyclaim',
            old_name='penalty',
            new_name='penalty_type',
        ),
    ]
