# Generated by Django 4.0.2 on 2022-03-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_penalty_penaltyclaim_penalty_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PenaltyClaim',
            new_name='Claim',
        ),
    ]
