# Generated by Django 4.0.4 on 2022-04-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_penaltyclaim_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
