# Generated by Django 4.0.4 on 2022-04-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='penalty',
            name='base_threshold',
            field=models.IntegerField(default=7200),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='penalty_type',
            field=models.CharField(choices=[('PD', 'Paid'), ('TL', 'Toil')], default='PD', max_length=2),
        ),
        migrations.CreateModel(
            name='TimesheetClaimRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('cost_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.costcode')),
                ('time_sheet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.timesheet')),
            ],
        ),
    ]
