# Generated by Django 4.0.4 on 2022-04-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_costcode_penalty_base_threshold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetclaimrow',
            old_name='units',
            new_name='seconds',
        ),
    ]
