# Generated by Django 4.0.4 on 2022-04-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_units_timesheetclaimrow_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='timesheet',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.timesheetclaim'),
        ),
    ]
